### ISSUE TITLE
improve mousemovement

### ISSUE THREAD

**Issue by NthnH** [CIOCOLATA47/AntiAfk#11]
The mousemovement could use a multiplier parameter (more extreme movement) and also a vertical movement
The server I play on requires both horizontal and vertical mouse movement (and it could be that a few pixels is not enough), which I already achieved with a macro but I dont want to keep my MC window active all the time

**Comment by CIOCOLATA47** [comment]
I will in a few days I am kinda busy

**Comment by CIOCOLATA47** [comment]
Aight i added it use /antiafk mousemovement <horizontalMultiplier> <verticalMultiplier> and /antiafk mousemovement to disable/enable it
