### ISSUE TITLE
Modrinth outdated commands and features description

### ISSUE THREAD

**Issue by vianneynara** [CIOCOLATA47/AntiAfk#4]
https://modrinth.com/mod/antiafk

The following link's content seem to be outdated as the mode does not come with the features described on the page. The mod itself assigns the player for ~5 seconds / ~50 ticks interval, while the commands does not seem to be working on servers, unlike other mods that uses client side commands.

**Comment by CIOCOLATA47** [comment]
I will fix it

**Comment by CIOCOLATA47** [comment]
The commands should now work on servers

**Comment by vianneynara** [comment]
Can confirm the commands now work on servers on version 1.0.8 (1.20.4). Thank you.
