### ISSUE TITLE
Add default settings

### ISSUE THREAD

**Issue by Antside** [CIOCOLATA47/AntiAfk#8]
This mod is perfect except for the fact that there are no default settings. I prefer the swing method instead of the jump method so it doesn't use up my food bar. However, it is a bit annoying to have to toggle jump off and toggle swing on each and every time. I would like a .txt file or something so I could set whatever I like as my default. Sorry if this already exists and I simply missed it

**Comment by CIOCOLATA47** [comment]
No worries i will add a config file in a few days when i have time i think i will also make a gui screen this summer
